FROM golang:1.16 as build
WORKDIR /go/src/
COPY tutorsapp-api /go/src/tutorsapp-api
# COPY ./utilities /go/src/tutorsapp-api/
ENV GO111MODULE=auto
ENV GOPATH=$HOME/go
ENV GOROOT=/usr/local/go
ENV PATH=$PATH:/usr/local/go/bin:$GOPATH/bin
RUN cd /go/src/tutorsapp-api/api-test && \ 
    go get ./... && \
    go build 
#RUN go build /go/src/tutorsapp-api/api-sys/

FROM alpine:latest
WORKDIR /opt/
RUN apk add --no-cache libc6-compat
COPY --from=build /go/src/tutorsapp-api/api-test/api-test  .
CMD ["./api-test"]
